spring.application.name=reservamedica
server.port=${SERVER_PORT:8083}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@dba001_tp?TNS_ADMIN=${ORACLE_WALLET_PATH:c:/Wallet_dba001}}
spring.datasource.username=FULLSTACK
spring.datasource.password=Fullst4ck......
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

logging.file.name=${LOG_FILE_NAME:reservamedica.log}